baseURL = 'https://clovernotes.co/'
languageCode = 'en-us'
title = 'Clover Notes'

theme = "charlolamode"

menu.main = [
	{ name = "Anime Reviews", url = "/animereviews" },
	{ name = "Blogs", url = "/blogs" },
	{ name = "Portfolio", url = "/portfolio"}
]

[services.rss]
limit = -1

[outputs]
blogs = ["html", "rss"]
portfolio = ["html"]
home = ["html"]

[params]
subtitle = "Probably the best website on the planet that was promised to Jews."
defaultTheme = "dark"
ShowShareButtons = true
ShowBreadCrumbs = false

profileMode.enabled = false
disableThemeToggle = true

[params.contact]
email = "ali.hussain.abid.246@outlook.com"
phone = "You really thing I'll put my number on the Internet 😒"
