baseURL = 'https://clovernotes.co/'
languageCode = 'en-us'
title = 'Clover Notes'
copyright = "© 2025, Clover Notes"
theme = "paper"

[taxonomies]
platform = "platforms"
tool = "tools"

menus.main = [
	{ Identifier = "Home", Name = "Home", Weight = 10, URL = "/" },
	{ Identifier = "Blogs", Name = "Blogs", Weight = 20, URL = "/blogs/" },
	{ Identifier = "Anime Reviews", Name = "Anime Reviews", Weight = 30, URL = "/animereviews/" },
	{ Identifier = "Portfolio", Name = "Portfolio", Weight = 40, URL = "/portfolio/" }
]

[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
lineNos = true


[params]
	# color style
	color = 'wheat'                            # linen, wheat, gray, light

	# header social icons
	github = 'blackmagezeraf'                 # github.com/YOUR_GITHUB_ID
	rss = true                                # show rss icon

	# home page profile
	avatar = 'blackwizardzeraf@gmail.com'     # gravatar email or image url
	name = 'Ali Hussain Abid'
	bio = 'Game Designer, Developer, and Writer'

	# misc
	disableHLJS = false                       # disable highlight.js
	disablePostNavigation = true             # disable post navigation
	monoDarkIcon = true                       # show monochrome dark mode icon
	math = true                               # enable KaTeX math typesetting globally
	localKatex = false                        # use local KaTeX js/css instead of CDN
	favicon = "favicon.ico"                   # customize the default favicon
	appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

	# RTL supprot
	direction = "ltr"                         # RTL support for Right-to-left languages