baseURL = "https://clovernotes.co/"
languageCode = "en-us"
title = "Clover Notes"
copyright = "© 2025, Clover Notes"
theme = "paper"

menus.main = [
	{ Identifier = "Blogs", Name = "Blogs", Weight = 20, URL = "/blogs/" },
	{ Identifier = "Anime Reviews", Name = "Anime Reviews", Weight = 30, URL = "/animereviews/" },
	{ Identifier = "Portfolio", Name = "Portfolio", Weight = 40, URL = "/portfolio/" }
]

[markup]
anchorLineNos = false
codeFences = true
guessSyntax = false
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4
wrapperClass = "highlight"

[params]
# color style
color = "wheat"

# header social icons
github = "blackmagezeraf"
rss = true

# home page profile
avatar = "blackwizardzeraf@gmail.com"
name = "Ali Hussain Abid"
bio = "Game Designer, Developer, and Writer"

# misc
disableHLJS = false
disablePostNavigation = true
monoDarkIcon = false
math = true
localKatex = false
favicon = "favicon.ico"
appleTouchIcon = "apple-touch-icon.png"

# RTL supprot
direction = "ltr"                         # RTL support for Right-to-left languages

[build]
buildStats.enable = false
